show_help() {
    case $1 in
    api | x25519 | tls | run | uuid | version)
        $is_core_bin help $1 ${@:2}
        ;;
    *)
        [[ $1 ]] && warn "unknown option '$1'"
        msg "sbx $is_sh_ver"
        msg "Usage: $is_sh_name [options]... [args]... "
        msg

        if [[ -f $is_core_dir/lang && $(cat $is_core_dir/lang) == "zh-TW" ]]; then
            show_help_zh
        else
            show_help_en
        fi

        msg "use del/ddel with caution — no confirmation"
        ;;
    esac
}

show_help_en() {
    msg "BASIC:"
    msg "  v, version                                      show version"
    msg "  ip                                              show server IP"
    msg "  pbk                                             generate reality keypair"
    msg "  get-port                                        get an available port"
    msg "  ss2022                                          generate ss2022 password"
    msg ""
    msg "CONFIG:"
    msg "  a, add [protocol] [args... | auto]              add config"
    msg "  c, change [name] [option] [args... | auto]      change config"
    msg "  d, del [name]                                   delete config"
    msg "  i, info [name]                                  view config"
    msg "  qr [name]                                       show QR code"
    msg "  url [name]                                      show URL"
    msg "  log                                             view log"
    msg ""
    msg "CHANGE:"
    msg "  full [name] [...]                               change multiple fields"
    msg "  id [name] [uuid | auto]                         change UUID"
    msg "  host [name] [domain]                            change domain"
    msg "  port [name] [port | auto]                       change port"
    msg "  path [name] [path | auto]                       change path"
    msg "  passwd [name] [password | auto]                 change password"
    msg "  key [name] [Private key | auto] [Public key]    change key"
    msg "  method [name] [method | auto]                   change encryption"
    msg "  sni [name] [ip | domain]                        change serverName"
    msg "  new [name] [...]                                change protocol"
    msg "  web [name] [domain]                             change proxy site"
    msg ""
    msg "DNS:"
    msg "  dns nextdns <id> [device]                       NextDNS + CF/GG fallback"
    msg "  dns cf                                           Cloudflare H3"
    msg "  dns gg                                           Google H3"
    msg "  dns 11 | 88 | family                             preset single server"
    msg "  dns set <address>                                custom DNS"
    msg "  dns none                                         clear DNS"
    msg ""
    msg "TOOLS:"
    msg "  speed [name|vps]                                speed test"
    msg "  check [name]                                    health check"
    msg "  traffic [name]                                  traffic stats"
    msg "  backup [list]                                   backup configs"
    msg "  restore <file>                                  restore from backup"
    msg "  lang [zh-TW|en]                                 switch language"
    msg ""
    msg "MANAGE:"
    msg "  un, uninstall                                   uninstall"
    msg "  u, update [core | sh | caddy] [ver]             update"
    msg "  U, update.sh                                    update script"
    msg "  s, status                                       service status"
    msg "  start, stop, restart [caddy]                    service control"
    msg "  t, test                                         test run"
    msg "  reinstall                                       reinstall"
    msg ""
    msg "OTHER:"
    msg "  debug [name]                                    debug info"
    msg "  gen [...]                                       generate JSON only (dry-run)"
    msg "  no-auto-tls [...]                               add config without auto TLS"
    msg "  bbr                                             enable BBR"
    msg "  bin [...]                                       run sing-box binary command"
    msg "  matrix [rain|logo]                              Matrix digital rain"
    msg "  [...] [...]                                     pass-through to sing-box"
    msg "  h, help                                         show this help"
}

show_help_zh() {
    msg "基本："
    msg "  v, version                                      顯示版本"
    msg "  ip                                              顯示主機 IP"
    msg "  pbk                                             產生 reality 金鑰"
    msg "  get-port                                        取得可用端口"
    msg "  ss2022                                          產生 ss2022 密碼"
    msg ""
    msg "配置："
    msg "  a, add [protocol] [args... | auto]              添加配置"
    msg "  c, change [name] [option] [args... | auto]      更改配置"
    msg "  d, del [name]                                   刪除配置"
    msg "  i, info [name]                                  查看配置"
    msg "  qr [name]                                       顯示 QR code"
    msg "  url [name]                                      顯示 URL"
    msg "  log                                             查看日誌"
    msg ""
    msg "更改："
    msg "  full [name] [...]                               更改多個參數"
    msg "  id [name] [uuid | auto]                         更改 UUID"
    msg "  host [name] [domain]                            更改域名"
    msg "  port [name] [port | auto]                       更改端口"
    msg "  path [name] [path | auto]                       更改路徑"
    msg "  passwd [name] [password | auto]                 更改密碼"
    msg "  key [name] [Private key | auto] [Public key]    更改金鑰"
    msg "  method [name] [method | auto]                   更改加密方式"
    msg "  sni [name] [ip | domain]                        更改 serverName"
    msg "  new [name] [...]                                更改協議"
    msg "  web [name] [domain]                             更改偽裝網站"
    msg ""
    msg "DNS："
    msg "  dns nextdns <id> [device]                       NextDNS + CF/GG 備援"
    msg "  dns cf                                           Cloudflare H3"
    msg "  dns gg                                           Google H3"
    msg "  dns 11 | 88 | family                             預設單伺服器"
    msg "  dns set <address>                               自訂 DNS"
    msg "  dns none                                        清除 DNS"
    msg ""
    msg "工具："
    msg "  speed [name|vps]                                測速"
    msg "  check [name]                                    健康檢查"
    msg "  traffic [name]                                  流量統計"
    msg "  backup [list]                                   備份配置"
    msg "  restore <file>                                  還原配置"
    msg "  lang [zh-TW|en]                                 切換語言"
    msg ""
    msg "管理："
    msg "  un, uninstall                                   卸載"
    msg "  u, update [core | sh | caddy] [ver]             更新"
    msg "  U, update.sh                                    更新腳本"
    msg "  s, status                                       服務狀態"
    msg "  start, stop, restart [caddy]                    啟動 / 停止 / 重啟"
    msg "  t, test                                         測試運行"
    msg "  reinstall                                       重裝腳本"
    msg ""
    msg "其他："
    msg "  debug [name]                                    debug 資訊"
    msg "  gen [...]                                       僅產生 JSON（不寫入）"
    msg "  no-auto-tls [...]                               添加配置（不自動 TLS）"
    msg "  bbr                                             啟用 BBR"
    msg "  bin [...]                                       執行 sing-box 指令"
    msg "  matrix [rain|logo]                              Matrix 數位雨"
    msg "  [...] [...]                                     傳遞給 sing-box 核心"
    msg "  h, help                                         顯示此幫助"
}

about() {
    msg
    msg " ${c_bright}┌─────────────────────────────────────────────┐${c_none}"
    msg " ${c_bright}│${c_none} ${c_dim}▀█▀ █▀▄ ▀ ▀${c_none}  ${c_bright}sbx ${is_sh_ver}${c_none}                    ${c_bright}│${c_none}"
    msg " ${c_bright}│${c_none} ${c_dim} █  █▀  ▀█▀${c_none}  ${c_dim}matrix terminal UI${c_none}          ${c_bright}│${c_none}"
    msg " ${c_bright}└─────────────────────────────────────────────┘${c_none}"
    msg

    if [[ -f $is_core_dir/lang && $(cat $is_core_dir/lang) == "zh-TW" ]]; then
        msg " sbx 是一個 sing-box 管理腳本"
        msg " 採用 Matrix 黑客帝國風格終端界面，支援多語言"
        msg ""
        msg " 功能："
        msg "  · 協議管理（REALITY / TUIC / Trojan / Hysteria2 等）"
        msg "  · NextDNS 多伺服器 DNS"
        msg "  · 測速 / 健康檢查 / 備份還原 / 流量統計"
        msg "  · 多語言界面（繁體中文 / English）"
        msg "  · 'sbx matrix' — 進入母體"
        msg ""
        msg " 作者: WAHSUN"
    else
        msg " sbx is a sing-box management script"
        msg " with Matrix-themed terminal UI and multi-language support"
        msg ""
        msg " Features:"
        msg "  · Protocol management (REALITY / TUIC / Trojan / Hysteria2 ...)"
        msg "  · NextDNS multi-server DNS"
        msg "  · Speed test / health check / backup & restore / traffic stats"
        msg "  · Multi-language UI (English / 繁體中文)"
        msg "  · 'sbx matrix' — enter the Matrix"
        msg ""
        msg " Author: WAHSUN"
    fi
    msg
}
